--- 
abstract: Simple, compact and correct param-checking functions
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Params-Util
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
  Scalar::Util: 1.14
  perl: 5.004
version: 0.27
