
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.14
name: Params-Util
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.42
  File::Spec: 0.80
requires: 
  Scalar::Util: 1.11
  perl: 5.005
  Exporter: 0
abstract: Simple, compact and correct param-checking functions
