
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.64
distribution_type: module
version: 0.20
name: Params-Util
author: Adam Kennedy <adamk@cpan.org>
license: perl
build_requires: 
  Test::More: 0.42
  File::Spec: 0.80
requires: 
  Scalar::Util: 1.14
  perl: 5.004
  Exporter: 0
abstract: Simple, compact and correct param-checking functions
